version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Mumma12@
      MYSQL_DATABASE: lms
      MYSQL_USER: root
      MYSQL_PASSWORD: Mumma12@
    volumes:
      - goinvest-volume:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080
  backend:
    image: backend_image:latest
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - 3000:3000
  frontend:
    image: frontend_image:latest
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  goinvest-volume: